on:
  push:
    branches:
      - master    
      - main
  pull_request:
    branches:
      - master    
      - main
  schedule:
  - cron: "0 0 * * *"
  
name: schedule-report

jobs:
  schedule-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      # https://github.com/r-lib/actions/issues/23
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}

      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)      
      - name: Generate data and rmd
        shell: Rscript {0}
        run: |
          source("R/job.R", echo = TRUE)
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "updating data and report"
          git push
