on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - master
      - main
  pull_request:
    branches
      - master
      - main

name: schedule-report

jobs:
  schedule-report:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
      - name: Generate data and rmd
        shell: Rscript {0}
        run: |
          source("R/job.R", echo = TRUE)
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "updating data and report"
          git push
